spring:
  application:
    name: clients

  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    password: secret
    username: manager
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8889